# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f4a477b087116bcf129eda5f93f671fc9117bbe4c3fd54206a4d5ca49cce5e9914379d7247a91411f499ffc6ca677772eeaa12dd975edcf3768afca99a7747

test:
  secret_key_base: 6cf18d45cc7ca927aedaf4f63682392a2b77187a82f2512dd03b93171c9b64ab36ef6169369d08bc021f860580212d928bd631022bc3a9c22dfe58ac33a28b2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
